### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by SkyAndCloud** [DAMO-NLP-SG/CLEX#2]
Hi, I have several questions about the implementation.
1. For [`scaled_inv_freq`](https://github.com/DAMO-NLP-SG/CLEX/blob/a48602f9cc8fbc6ffad58a1d55d19b027e793f1e/CLEX/clex_layer.py#L128) during the validation, as I understand, it should be `scale_inv_freq = self.freq_cached[int(t_val)]`. It does't need to subtract `1`.
2. In [L97](https://github.com/DAMO-NLP-SG/CLEX/blob/a48602f9cc8fbc6ffad58a1d55d19b027e793f1e/CLEX/clex_layer.py#L97), if `seq_len < self.max_position_embeddings`, `scale_factor` would be zero so that L104 would encounter divide-zero error. It seems that `//` should be replaced with `/` for L97 and L105.
3. In `ODELinear`
    - In L31, why assign `alpha = 2 * t - 1` other than `t`? 
    - In L35, the calculation of `delta_ntk_freq` was not found at the paper, which is $$-\frac{2i}{d-2} \cdot 10000^{\frac i d} \cdot \alpha^{\frac{i}{d-2}+1}$$
    - In L40-41, why `x` plus `torch.log(time)` and `time_embed = delta_time / time`? I feel a bit confused when comparing it with paper's Eq. (14).

**Comment by guanzhchen** [comment]
Hi, thanks for your interest!

1. The odeint would return a list corresponding to the `time_grid`. Our `time_grid` is set as `[1, 2, ..., max_t+1]`, so for a specific t_val (e.g., 3), its `scaled_inv_freq` should be `self.freq_cached[2]`. That's why we need to subtract 1.
2. Thanks for your feedback! We now fix it by setting the minimum `scale_factor` as 1.  The reason why we use `//` is that we only sample `t_val` of integers during training, but I guess it should also make sense if use `/`.
3.1.  The setting of `alpha` is inspired by [DynamicNTKScaling](https://www.reddit.com/r/LocalLLaMA/comments/14mrgpr/dynamically_scaled_rope_further_increases/), where the scaling factor is set as 2, so the refined t would be `2*t - (2-1) = 2t-1`. The name `alpha` may be a little confused, sorry.
3.2. `delta_ntk_freq ` is not meaningful. This is the intermediate result of the derivative for scalar embedding in Equation (14). Please check the Eq. (14) in  our newest [ICLR paper](https://openreview.net/pdf?id=wXpSidPpc5), where we give a finally simplified form `time_embed`. (Sorry for the complex code implementation.)
3.3. The `time_embed` is the scalar embedding in Eq. (14) and the plus of `torch.log(time)` is set for identifying the current t. These operations are both set for integrating the NTK-scaled RoPE as a start point.

Feel free to let me know if you have more questions.
